import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../api';
import Navbar from '../components/Navbar';
import Spinner from '../components/Spinner';
import { apiErrorMessage } from '../api';

const initial = { eventType: '', guestCount: '', budget: '', location: '', date: '', vibe: '', templateId: '' };

export default function NewEvent() {
  const navigate = useNavigate(); const [form, setForm] = useState(initial); const [templates, setTemplates] = useState([]); const [templatesLoading, setTemplatesLoading] = useState(true); const [templatesError, setTemplatesError] = useState(''); const [plan, setPlan] = useState(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.get('/templates').then(({ data }) => setTemplates(data)).catch((err) => setTemplatesError(apiErrorMessage(err, 'Unable to load occasion templates.'))).finally(() => setTemplatesLoading(false)); }, []);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const selectTemplate = (template) => { setForm((current) => ({ ...current, ...template.defaults, templateId: template.id })); setPlan(null); setError(''); };
  const clearTemplate = () => { setForm((current) => ({ ...initial, location: current.location, date: current.date })); setPlan(null); setError(''); };
  const generate = async (event) => { event.preventDefault(); if (form.eventType.trim().length < 3) return setError('Describe the event using at least 3 characters.'); if (!Number.isInteger(Number(form.guestCount)) || Number(form.guestCount) <= 0) return setError('Guest count must be a positive whole number.'); if (!Number.isFinite(Number(form.budget)) || Number(form.budget) <= 0) return setError('Budget must be greater than zero.'); if (!form.location.trim()) return setError('Add a location for the event.'); setLoading(true); setError(''); try { const { data } = await api.post('/ai/plan', { ...form, guestCount: Number(form.guestCount), budget: Number(form.budget) }); setPlan(data); } catch (err) { setError(apiErrorMessage(err, 'Unable to generate a plan. Try again in a moment.')); } finally { setLoading(false); } };
  const save = async () => { if (!plan) return setError('Generate a plan before saving.'); setSaving(true); setError(''); try { const { data } = await api.post('/events', { ...plan, location: form.location.trim(), date: form.date || undefined, templateId: form.templateId || undefined, budget: Number(form.budget), guestCount: Number(form.guestCount) }); navigate(`/events/${data._id}`); } catch (err) { setError(apiErrorMessage(err, 'Unable to save this event.')); } finally { setSaving(false); } };
  return <><Navbar /><main className="page-shell"><Link className="back-link" to="/">← Back to events</Link><div className="page-heading compact"><div><p className="eyebrow">NEW BLUEPRINT</p><h1>Plan something memorable.</h1><p>Give us the shape of the occasion. We’ll fill in the thoughtful details.</p></div></div><section className="template-section"><div className="section-heading"><div><p className="eyebrow">STARTING POINT</p><h2>Choose an occasion</h2></div></div>{templatesLoading ? <Spinner label="Loading templates" /> : templatesError ? <p className="error" role="alert">{templatesError}</p> : <div className="template-grid"><button type="button" className={!form.templateId ? 'template-card selected' : 'template-card'} onClick={clearTemplate}><span className="template-emoji">✦</span><strong>Start from scratch</strong><span>Build a custom plan from a blank brief.</span></button>{templates.map((template) => <button type="button" className={form.templateId === template.id ? 'template-card selected' : 'template-card'} key={template.id} onClick={() => selectTemplate(template)}><span className="template-emoji">{template.emoji}</span><strong>{template.name}</strong><span>{template.description}</span></button>)}</div>}</section><section className="planner-layout"><form className="form-panel" onSubmit={generate}><h2>Event brief</h2><label>What are you planning?<input required minLength="3" placeholder="e.g. rooftop birthday dinner" value={form.eventType} onChange={(e) => update('eventType', e.target.value)} /></label><div className="two-col"><label>Guests<input required type="number" min="1" step="1" placeholder="40" value={form.guestCount} onChange={(e) => update('guestCount', e.target.value)} /></label><label>Budget (INR)<input required type="number" min="1" step="0.01" placeholder="50000" value={form.budget} onChange={(e) => update('budget', e.target.value)} /></label></div><div className="two-col"><label>Location<input required placeholder="Mumbai, Maharashtra" value={form.location} onChange={(e) => update('location', e.target.value)} /></label><label>Date<input type="date" value={form.date} onChange={(e) => update('date', e.target.value)} /></label></div><label>Vibe <span className="optional">optional</span><textarea rows="3" placeholder="Warm, elegant, low-key..." value={form.vibe} onChange={(e) => update('vibe', e.target.value)} /></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary-button wide" disabled={loading}>{loading ? 'Building your plan...' : '✦ Generate with AI'}</button>{loading && <Spinner label="Thinking through the details" />}</form><section className="preview-panel">{plan ? <PlanPreview plan={plan} onSave={save} saving={saving} /> : <div className="preview-empty"><span>✦</span><h2>Your plan will appear here.</h2><p>Generate a plan to review the agenda, checklist, and budget before saving it.</p></div>}</section></section></main></>;
}

export function PlanPreview({ plan, onSave, saving }) { return <div className="plan-preview"><div className="preview-header"><div><p className="eyebrow">AI DRAFT</p><h2>{plan.title}</h2></div><button className="primary-button" onClick={onSave} disabled={saving}>{saving ? 'Saving...' : 'Save event'}</button></div><p className="plan-description">{plan.description}</p><div className="preview-section"><h3>Agenda</h3>{plan.agenda.map((item, index) => <div className="agenda-row" key={`${item.time}-${index}`}><strong>{item.time}</strong><span>{item.activity}</span></div>)}</div><div className="preview-section"><h3>Checklist</h3><ul className="clean-list">{plan.checklist.map((item, index) => <li key={`${item.task}-${index}`}>{item.task}</li>)}</ul></div><div className="preview-section"><h3>Budget split</h3>{plan.budgetSplit.map((item) => <div className="budget-row" key={item.category}><span>{item.category}</span><strong>₹{Number(item.amount).toLocaleString('en-IN')}</strong></div>)}</div></div>; }
